### PR TITLE
Guard destructuring

### LINKED ISSUE #1326: [Bug][Filing] Failed destructuring in receiveLatestSubmission and receiveFiling
- App hangs when no submissions exist for a Filing

### PR DESCRIPTION
**Pull request by meissadia**
Closes #1326 

## Changes
- Stalled Upload check - guard destructuring to avoid error
- Institutions: Add Filing Period and fallback where appropriate

## Testing
- Start HMDA Platform / Institutions API locally
- Frontend on `master`: `yarn ci-data && yarn ci`
- Visit http://localhost:3000/filing and observe that institutions are stuck in loading status for all periods
- Frontend: `git checkout 1326-bad-destructure`
- Visit http://localhost:3000/filing and observe that institutions are loading for all periods

### CODE REVIEW

File: src/filing/actions/receiveFiling.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { isStalledUpload } from '../institutions/helpers'
 
 export default function receiveFiling(data) {
   // Check for stalled uploads
-  data.submissions = data.submissions.map((sub) => {
+  data.submissions = data.submissions?.map((sub) => {
```
Comment (lchen-2101) [inline src/filing/actions/receiveFiling.js:7]: think we should try to avoid side-effects if we are able to. feels like this one can be done with:
`const filing = {...data, submissions: data.submissions?.map...}` rather than modifying `data.submissions`

File: src/filing/actions/receiveLatestSubmission.js [hunk 2]
```diff
@@ -1,8 +1,10 @@
 import { RECEIVE_LATEST_SUBMISSION } from '../constants/index'
+import { UNINITIALIZED } from '../constants/statusCodes'
 import { isStalledUpload } from '../institutions/helpers'
 
 export default function receiveLatestSubmission(action) {
-  const { status: { code }, start } = action
+  const { start } = action
+  let code = action.status?.code || UNINITIALIZED
```
Comment (lchen-2101) [inline src/filing/actions/receiveLatestSubmission.js:7]: `code` doesn't get changed, right? can this be `const`?

File: src/filing/actions/receiveFiling.js (hunk 1 above)
Comment (meissadia) [reply src/filing/actions/receiveFiling.js]: Good catch, thanks for the keen eye!

**Review by lchen-2101 — APPROVED** [review]
LGTM
